name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Changelog
    runs-on: ubuntu-latest
    steps:
      - name: Check out code using Git
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits

      - name: Set Node version to 14
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --frozen-lockfile --ignore-engines
        env:
          CI: true

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
